name: Publish Package to Github packages

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish-github-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm ci --include=dev
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
